[package]
name = "reflme-server"
version = "0.1.0"
authors = ["Max Gonzih <gonzih@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.2"
rocket_contrib = "0.4.2"
serde_json = "1.0"
serde_derive = "1.0"
serde = "1.0.101"
